
title: Bart Resume
url: 'http://bomcat.tistory.com'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
style: styles-toss

#Profile information
name: Bart(이철민)
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: elfinx@gmail.com
website: bomcat.tistory.com #do not add http://
linkedin: bart-lee
github: elfinxx
twitter: '@elfinxx'

#Update all the sections by editing the files inside _includes folder.
